import * as React from "react";
import { BaseAutocompleteLogic, BaseAutocompleteLogicOptions, BaseAutocompleteLogicStatus } from "@autocomplete/core";
interface AutocompleteWrapperArgs extends BaseAutocompleteLogicStatus {
    wrapperInputProps: (props?: React.HTMLProps<HTMLInputElement> | any, options?: any) => React.HTMLProps<HTMLInputElement>;
    isOpen: boolean;
    removeValue: Function;
    addOption: any;
    optionToDisplay: Function;
    optionToKey: Function;
    valueToDisplay: Function;
    valueToKey: Function;
    wrapperOptionProps: (key: number | string, props?: React.HTMLProps<HTMLInputElement> | any) => React.HTMLProps<HTMLInputElement>;
}
export interface AutocompleteWrapperProps extends BaseAutocompleteLogicOptions<any> {
    multi?: boolean;
    notBlurAfterEnter?: boolean;
    optionsContainerRef?: any;
    children?: (args: AutocompleteWrapperArgs) => any;
}
export declare class AutocompleteWrapper extends React.Component<AutocompleteWrapperProps, any> {
    autoLogic: BaseAutocompleteLogic<any>;
    refMap: Map<any, any>;
    inputRef: any;
    constructor(props: any);
    blurInput: () => void;
    markedChangeHandler: ({ key, index, option }: {
        key: any;
        index: any;
        option: any;
    }) => void;
    wrapperInputProps: (props?: React.HTMLProps<HTMLInputElement>, options?: any) => {
        onKeyDown: (e: any) => void;
        onChange: (e: any) => void;
        onBlur: (e: any) => void;
        onFocus: (e: any) => void;
        accept?: string;
        acceptCharset?: string;
        action?: string;
        allowFullScreen?: boolean;
        allowTransparency?: boolean;
        alt?: string;
        as?: string;
        async?: boolean;
        autoComplete?: string;
        autoFocus?: boolean;
        autoPlay?: boolean;
        capture?: string | boolean;
        cellPadding?: string | number;
        cellSpacing?: string | number;
        charSet?: string;
        challenge?: string;
        checked?: boolean;
        cite?: string;
        classID?: string;
        cols?: number;
        colSpan?: number;
        content?: string;
        controls?: boolean;
        coords?: string;
        crossOrigin?: string;
        data?: string;
        dateTime?: string;
        default?: boolean;
        defer?: boolean;
        disabled?: boolean;
        download?: any;
        encType?: string;
        form?: string;
        formAction?: string;
        formEncType?: string;
        formMethod?: string;
        formNoValidate?: boolean;
        formTarget?: string;
        frameBorder?: string | number;
        headers?: string;
        height?: string | number;
        high?: number;
        href?: string;
        hrefLang?: string;
        htmlFor?: string;
        httpEquiv?: string;
        integrity?: string;
        keyParams?: string;
        keyType?: string;
        kind?: string;
        label?: string;
        list?: string;
        loop?: boolean;
        low?: number;
        manifest?: string;
        marginHeight?: number;
        marginWidth?: number;
        max?: string | number;
        maxLength?: number;
        media?: string;
        mediaGroup?: string;
        method?: string;
        min?: string | number;
        minLength?: number;
        multiple?: boolean;
        muted?: boolean;
        name?: string;
        nonce?: string;
        noValidate?: boolean;
        open?: boolean;
        optimum?: number;
        pattern?: string;
        placeholder?: string;
        playsInline?: boolean;
        poster?: string;
        preload?: string;
        readOnly?: boolean;
        rel?: string;
        required?: boolean;
        reversed?: boolean;
        rows?: number;
        rowSpan?: number;
        sandbox?: string;
        scope?: string;
        scoped?: boolean;
        scrolling?: string;
        seamless?: boolean;
        selected?: boolean;
        shape?: string;
        size?: number;
        sizes?: string;
        span?: number;
        src?: string;
        srcDoc?: string;
        srcLang?: string;
        srcSet?: string;
        start?: number;
        step?: string | number;
        summary?: string;
        target?: string;
        type?: string;
        useMap?: string;
        value?: string | number | string[];
        width?: string | number;
        wmode?: string;
        wrap?: string;
        defaultChecked?: boolean;
        defaultValue?: string | number | string[];
        suppressContentEditableWarning?: boolean;
        suppressHydrationWarning?: boolean;
        accessKey?: string;
        className?: string;
        contentEditable?: boolean | "true" | "false" | "inherit";
        contextMenu?: string;
        dir?: string;
        draggable?: boolean | "true" | "false";
        hidden?: boolean;
        id?: string;
        lang?: string;
        slot?: string;
        spellCheck?: boolean | "true" | "false";
        style?: React.CSSProperties;
        tabIndex?: number;
        title?: string;
        translate?: "yes" | "no";
        radioGroup?: string;
        role?: string;
        about?: string;
        datatype?: string;
        inlist?: any;
        prefix?: string;
        property?: string;
        resource?: string;
        typeof?: string;
        vocab?: string;
        autoCapitalize?: string;
        autoCorrect?: string;
        autoSave?: string;
        color?: string;
        itemProp?: string;
        itemScope?: boolean;
        itemType?: string;
        itemID?: string;
        itemRef?: string;
        results?: number;
        security?: string;
        unselectable?: "on" | "off";
        inputMode?: "text" | "none" | "tel" | "url" | "email" | "numeric" | "decimal" | "search";
        is?: string;
        'aria-activedescendant'?: string;
        'aria-atomic'?: boolean | "true" | "false";
        'aria-autocomplete'?: "list" | "none" | "inline" | "both";
        'aria-busy'?: boolean | "true" | "false";
        'aria-checked'?: boolean | "true" | "false" | "mixed";
        'aria-colcount'?: number;
        'aria-colindex'?: number;
        'aria-colspan'?: number;
        'aria-controls'?: string;
        'aria-current'?: boolean | "time" | "step" | "true" | "false" | "page" | "location" | "date";
        'aria-describedby'?: string;
        'aria-details'?: string;
        'aria-disabled'?: boolean | "true" | "false";
        'aria-dropeffect'?: "link" | "none" | "copy" | "execute" | "move" | "popup";
        'aria-errormessage'?: string;
        'aria-expanded'?: boolean | "true" | "false";
        'aria-flowto'?: string;
        'aria-grabbed'?: boolean | "true" | "false";
        'aria-haspopup'?: boolean | "dialog" | "menu" | "true" | "false" | "listbox" | "tree" | "grid";
        'aria-hidden'?: boolean | "true" | "false";
        'aria-invalid'?: boolean | "true" | "false" | "grammar" | "spelling";
        'aria-keyshortcuts'?: string;
        'aria-label'?: string;
        'aria-labelledby'?: string;
        'aria-level'?: number;
        'aria-live'?: "off" | "assertive" | "polite";
        'aria-modal'?: boolean | "true" | "false";
        'aria-multiline'?: boolean | "true" | "false";
        'aria-multiselectable'?: boolean | "true" | "false";
        'aria-orientation'?: "horizontal" | "vertical";
        'aria-owns'?: string;
        'aria-placeholder'?: string;
        'aria-posinset'?: number;
        'aria-pressed'?: boolean | "true" | "false" | "mixed";
        'aria-readonly'?: boolean | "true" | "false";
        'aria-relevant'?: "text" | "additions" | "additions text" | "all" | "removals";
        'aria-required'?: boolean | "true" | "false";
        'aria-roledescription'?: string;
        'aria-rowcount'?: number;
        'aria-rowindex'?: number;
        'aria-rowspan'?: number;
        'aria-selected'?: boolean | "true" | "false";
        'aria-setsize'?: number;
        'aria-sort'?: "none" | "ascending" | "descending" | "other";
        'aria-valuemax'?: number;
        'aria-valuemin'?: number;
        'aria-valuenow'?: number;
        'aria-valuetext'?: string;
        children?: React.ReactNode;
        dangerouslySetInnerHTML?: {
            __html: string;
        };
        onCopy?: (event: React.ClipboardEvent<HTMLInputElement>) => void;
        onCopyCapture?: (event: React.ClipboardEvent<HTMLInputElement>) => void;
        onCut?: (event: React.ClipboardEvent<HTMLInputElement>) => void;
        onCutCapture?: (event: React.ClipboardEvent<HTMLInputElement>) => void;
        onPaste?: (event: React.ClipboardEvent<HTMLInputElement>) => void;
        onPasteCapture?: (event: React.ClipboardEvent<HTMLInputElement>) => void;
        onCompositionEnd?: (event: React.CompositionEvent<HTMLInputElement>) => void;
        onCompositionEndCapture?: (event: React.CompositionEvent<HTMLInputElement>) => void;
        onCompositionStart?: (event: React.CompositionEvent<HTMLInputElement>) => void;
        onCompositionStartCapture?: (event: React.CompositionEvent<HTMLInputElement>) => void;
        onCompositionUpdate?: (event: React.CompositionEvent<HTMLInputElement>) => void;
        onCompositionUpdateCapture?: (event: React.CompositionEvent<HTMLInputElement>) => void;
        onFocusCapture?: (event: React.FocusEvent<HTMLInputElement>) => void;
        onBlurCapture?: (event: React.FocusEvent<HTMLInputElement>) => void;
        onChangeCapture?: (event: React.FormEvent<HTMLInputElement>) => void;
        onBeforeInput?: (event: React.FormEvent<HTMLInputElement>) => void;
        onBeforeInputCapture?: (event: React.FormEvent<HTMLInputElement>) => void;
        onInput?: (event: React.FormEvent<HTMLInputElement>) => void;
        onInputCapture?: (event: React.FormEvent<HTMLInputElement>) => void;
        onReset?: (event: React.FormEvent<HTMLInputElement>) => void;
        onResetCapture?: (event: React.FormEvent<HTMLInputElement>) => void;
        onSubmit?: (event: React.FormEvent<HTMLInputElement>) => void;
        onSubmitCapture?: (event: React.FormEvent<HTMLInputElement>) => void;
        onInvalid?: (event: React.FormEvent<HTMLInputElement>) => void;
        onInvalidCapture?: (event: React.FormEvent<HTMLInputElement>) => void;
        onLoad?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onLoadCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onError?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onErrorCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onKeyDownCapture?: (event: React.KeyboardEvent<HTMLInputElement>) => void;
        onKeyPress?: (event: React.KeyboardEvent<HTMLInputElement>) => void;
        onKeyPressCapture?: (event: React.KeyboardEvent<HTMLInputElement>) => void;
        onKeyUp?: (event: React.KeyboardEvent<HTMLInputElement>) => void;
        onKeyUpCapture?: (event: React.KeyboardEvent<HTMLInputElement>) => void;
        onAbort?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onAbortCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onCanPlay?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onCanPlayCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onCanPlayThrough?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onCanPlayThroughCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onDurationChange?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onDurationChangeCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onEmptied?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onEmptiedCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onEncrypted?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onEncryptedCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onEnded?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onEndedCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onLoadedData?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onLoadedDataCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onLoadedMetadata?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onLoadedMetadataCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onLoadStart?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onLoadStartCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onPause?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onPauseCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onPlay?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onPlayCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onPlaying?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onPlayingCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onProgress?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onProgressCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onRateChange?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onRateChangeCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onSeeked?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onSeekedCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onSeeking?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onSeekingCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onStalled?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onStalledCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onSuspend?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onSuspendCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onTimeUpdate?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onTimeUpdateCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onVolumeChange?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onVolumeChangeCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onWaiting?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onWaitingCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onAuxClick?: (event: React.MouseEvent<HTMLInputElement, MouseEvent>) => void;
        onAuxClickCapture?: (event: React.MouseEvent<HTMLInputElement, MouseEvent>) => void;
        onClick?: (event: React.MouseEvent<HTMLInputElement, MouseEvent>) => void;
        onClickCapture?: (event: React.MouseEvent<HTMLInputElement, MouseEvent>) => void;
        onContextMenu?: (event: React.MouseEvent<HTMLInputElement, MouseEvent>) => void;
        onContextMenuCapture?: (event: React.MouseEvent<HTMLInputElement, MouseEvent>) => void;
        onDoubleClick?: (event: React.MouseEvent<HTMLInputElement, MouseEvent>) => void;
        onDoubleClickCapture?: (event: React.MouseEvent<HTMLInputElement, MouseEvent>) => void;
        onDrag?: (event: React.DragEvent<HTMLInputElement>) => void;
        onDragCapture?: (event: React.DragEvent<HTMLInputElement>) => void;
        onDragEnd?: (event: React.DragEvent<HTMLInputElement>) => void;
        onDragEndCapture?: (event: React.DragEvent<HTMLInputElement>) => void;
        onDragEnter?: (event: React.DragEvent<HTMLInputElement>) => void;
        onDragEnterCapture?: (event: React.DragEvent<HTMLInputElement>) => void;
        onDragExit?: (event: React.DragEvent<HTMLInputElement>) => void;
        onDragExitCapture?: (event: React.DragEvent<HTMLInputElement>) => void;
        onDragLeave?: (event: React.DragEvent<HTMLInputElement>) => void;
        onDragLeaveCapture?: (event: React.DragEvent<HTMLInputElement>) => void;
        onDragOver?: (event: React.DragEvent<HTMLInputElement>) => void;
        onDragOverCapture?: (event: React.DragEvent<HTMLInputElement>) => void;
        onDragStart?: (event: React.DragEvent<HTMLInputElement>) => void;
        onDragStartCapture?: (event: React.DragEvent<HTMLInputElement>) => void;
        onDrop?: (event: React.DragEvent<HTMLInputElement>) => void;
        onDropCapture?: (event: React.DragEvent<HTMLInputElement>) => void;
        onMouseDown?: (event: React.MouseEvent<HTMLInputElement, MouseEvent>) => void;
        onMouseDownCapture?: (event: React.MouseEvent<HTMLInputElement, MouseEvent>) => void;
        onMouseEnter?: (event: React.MouseEvent<HTMLInputElement, MouseEvent>) => void;
        onMouseLeave?: (event: React.MouseEvent<HTMLInputElement, MouseEvent>) => void;
        onMouseMove?: (event: React.MouseEvent<HTMLInputElement, MouseEvent>) => void;
        onMouseMoveCapture?: (event: React.MouseEvent<HTMLInputElement, MouseEvent>) => void;
        onMouseOut?: (event: React.MouseEvent<HTMLInputElement, MouseEvent>) => void;
        onMouseOutCapture?: (event: React.MouseEvent<HTMLInputElement, MouseEvent>) => void;
        onMouseOver?: (event: React.MouseEvent<HTMLInputElement, MouseEvent>) => void;
        onMouseOverCapture?: (event: React.MouseEvent<HTMLInputElement, MouseEvent>) => void;
        onMouseUp?: (event: React.MouseEvent<HTMLInputElement, MouseEvent>) => void;
        onMouseUpCapture?: (event: React.MouseEvent<HTMLInputElement, MouseEvent>) => void;
        onSelect?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onSelectCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onTouchCancel?: (event: React.TouchEvent<HTMLInputElement>) => void;
        onTouchCancelCapture?: (event: React.TouchEvent<HTMLInputElement>) => void;
        onTouchEnd?: (event: React.TouchEvent<HTMLInputElement>) => void;
        onTouchEndCapture?: (event: React.TouchEvent<HTMLInputElement>) => void;
        onTouchMove?: (event: React.TouchEvent<HTMLInputElement>) => void;
        onTouchMoveCapture?: (event: React.TouchEvent<HTMLInputElement>) => void;
        onTouchStart?: (event: React.TouchEvent<HTMLInputElement>) => void;
        onTouchStartCapture?: (event: React.TouchEvent<HTMLInputElement>) => void;
        onPointerDown?: (event: React.PointerEvent<HTMLInputElement>) => void;
        onPointerDownCapture?: (event: React.PointerEvent<HTMLInputElement>) => void;
        onPointerMove?: (event: React.PointerEvent<HTMLInputElement>) => void;
        onPointerMoveCapture?: (event: React.PointerEvent<HTMLInputElement>) => void;
        onPointerUp?: (event: React.PointerEvent<HTMLInputElement>) => void;
        onPointerUpCapture?: (event: React.PointerEvent<HTMLInputElement>) => void;
        onPointerCancel?: (event: React.PointerEvent<HTMLInputElement>) => void;
        onPointerCancelCapture?: (event: React.PointerEvent<HTMLInputElement>) => void;
        onPointerEnter?: (event: React.PointerEvent<HTMLInputElement>) => void;
        onPointerEnterCapture?: (event: React.PointerEvent<HTMLInputElement>) => void;
        onPointerLeave?: (event: React.PointerEvent<HTMLInputElement>) => void;
        onPointerLeaveCapture?: (event: React.PointerEvent<HTMLInputElement>) => void;
        onPointerOver?: (event: React.PointerEvent<HTMLInputElement>) => void;
        onPointerOverCapture?: (event: React.PointerEvent<HTMLInputElement>) => void;
        onPointerOut?: (event: React.PointerEvent<HTMLInputElement>) => void;
        onPointerOutCapture?: (event: React.PointerEvent<HTMLInputElement>) => void;
        onGotPointerCapture?: (event: React.PointerEvent<HTMLInputElement>) => void;
        onGotPointerCaptureCapture?: (event: React.PointerEvent<HTMLInputElement>) => void;
        onLostPointerCapture?: (event: React.PointerEvent<HTMLInputElement>) => void;
        onLostPointerCaptureCapture?: (event: React.PointerEvent<HTMLInputElement>) => void;
        onScroll?: (event: React.UIEvent<HTMLInputElement>) => void;
        onScrollCapture?: (event: React.UIEvent<HTMLInputElement>) => void;
        onWheel?: (event: React.WheelEvent<HTMLInputElement>) => void;
        onWheelCapture?: (event: React.WheelEvent<HTMLInputElement>) => void;
        onAnimationStart?: (event: React.AnimationEvent<HTMLInputElement>) => void;
        onAnimationStartCapture?: (event: React.AnimationEvent<HTMLInputElement>) => void;
        onAnimationEnd?: (event: React.AnimationEvent<HTMLInputElement>) => void;
        onAnimationEndCapture?: (event: React.AnimationEvent<HTMLInputElement>) => void;
        onAnimationIteration?: (event: React.AnimationEvent<HTMLInputElement>) => void;
        onAnimationIterationCapture?: (event: React.AnimationEvent<HTMLInputElement>) => void;
        onTransitionEnd?: (event: React.TransitionEvent<HTMLInputElement>) => void;
        onTransitionEndCapture?: (event: React.TransitionEvent<HTMLInputElement>) => void;
        key?: string | number;
    };
    wrapperOptionProps: (key: any, props?: React.HTMLProps<HTMLInputElement>) => {
        onClick: (e: any) => void;
        ref: (_ref: any) => void;
        accept?: string;
        acceptCharset?: string;
        action?: string;
        allowFullScreen?: boolean;
        allowTransparency?: boolean;
        alt?: string;
        as?: string;
        async?: boolean;
        autoComplete?: string;
        autoFocus?: boolean;
        autoPlay?: boolean;
        capture?: string | boolean;
        cellPadding?: string | number;
        cellSpacing?: string | number;
        charSet?: string;
        challenge?: string;
        checked?: boolean;
        cite?: string;
        classID?: string;
        cols?: number;
        colSpan?: number;
        content?: string;
        controls?: boolean;
        coords?: string;
        crossOrigin?: string;
        data?: string;
        dateTime?: string;
        default?: boolean;
        defer?: boolean;
        disabled?: boolean;
        download?: any;
        encType?: string;
        form?: string;
        formAction?: string;
        formEncType?: string;
        formMethod?: string;
        formNoValidate?: boolean;
        formTarget?: string;
        frameBorder?: string | number;
        headers?: string;
        height?: string | number;
        high?: number;
        href?: string;
        hrefLang?: string;
        htmlFor?: string;
        httpEquiv?: string;
        integrity?: string;
        keyParams?: string;
        keyType?: string;
        kind?: string;
        label?: string;
        list?: string;
        loop?: boolean;
        low?: number;
        manifest?: string;
        marginHeight?: number;
        marginWidth?: number;
        max?: string | number;
        maxLength?: number;
        media?: string;
        mediaGroup?: string;
        method?: string;
        min?: string | number;
        minLength?: number;
        multiple?: boolean;
        muted?: boolean;
        name?: string;
        nonce?: string;
        noValidate?: boolean;
        open?: boolean;
        optimum?: number;
        pattern?: string;
        placeholder?: string;
        playsInline?: boolean;
        poster?: string;
        preload?: string;
        readOnly?: boolean;
        rel?: string;
        required?: boolean;
        reversed?: boolean;
        rows?: number;
        rowSpan?: number;
        sandbox?: string;
        scope?: string;
        scoped?: boolean;
        scrolling?: string;
        seamless?: boolean;
        selected?: boolean;
        shape?: string;
        size?: number;
        sizes?: string;
        span?: number;
        src?: string;
        srcDoc?: string;
        srcLang?: string;
        srcSet?: string;
        start?: number;
        step?: string | number;
        summary?: string;
        target?: string;
        type?: string;
        useMap?: string;
        value?: string | number | string[];
        width?: string | number;
        wmode?: string;
        wrap?: string;
        defaultChecked?: boolean;
        defaultValue?: string | number | string[];
        suppressContentEditableWarning?: boolean;
        suppressHydrationWarning?: boolean;
        accessKey?: string;
        className?: string;
        contentEditable?: boolean | "true" | "false" | "inherit";
        contextMenu?: string;
        dir?: string;
        draggable?: boolean | "true" | "false";
        hidden?: boolean;
        id?: string;
        lang?: string;
        slot?: string;
        spellCheck?: boolean | "true" | "false";
        style?: React.CSSProperties;
        tabIndex?: number;
        title?: string;
        translate?: "yes" | "no";
        radioGroup?: string;
        role?: string;
        about?: string;
        datatype?: string;
        inlist?: any;
        prefix?: string;
        property?: string;
        resource?: string;
        typeof?: string;
        vocab?: string;
        autoCapitalize?: string;
        autoCorrect?: string;
        autoSave?: string;
        color?: string;
        itemProp?: string;
        itemScope?: boolean;
        itemType?: string;
        itemID?: string;
        itemRef?: string;
        results?: number;
        security?: string;
        unselectable?: "on" | "off";
        inputMode?: "text" | "none" | "tel" | "url" | "email" | "numeric" | "decimal" | "search";
        is?: string;
        'aria-activedescendant'?: string;
        'aria-atomic'?: boolean | "true" | "false";
        'aria-autocomplete'?: "list" | "none" | "inline" | "both";
        'aria-busy'?: boolean | "true" | "false";
        'aria-checked'?: boolean | "true" | "false" | "mixed";
        'aria-colcount'?: number;
        'aria-colindex'?: number;
        'aria-colspan'?: number;
        'aria-controls'?: string;
        'aria-current'?: boolean | "time" | "step" | "true" | "false" | "page" | "location" | "date";
        'aria-describedby'?: string;
        'aria-details'?: string;
        'aria-disabled'?: boolean | "true" | "false";
        'aria-dropeffect'?: "link" | "none" | "copy" | "execute" | "move" | "popup";
        'aria-errormessage'?: string;
        'aria-expanded'?: boolean | "true" | "false";
        'aria-flowto'?: string;
        'aria-grabbed'?: boolean | "true" | "false";
        'aria-haspopup'?: boolean | "dialog" | "menu" | "true" | "false" | "listbox" | "tree" | "grid";
        'aria-hidden'?: boolean | "true" | "false";
        'aria-invalid'?: boolean | "true" | "false" | "grammar" | "spelling";
        'aria-keyshortcuts'?: string;
        'aria-label'?: string;
        'aria-labelledby'?: string;
        'aria-level'?: number;
        'aria-live'?: "off" | "assertive" | "polite";
        'aria-modal'?: boolean | "true" | "false";
        'aria-multiline'?: boolean | "true" | "false";
        'aria-multiselectable'?: boolean | "true" | "false";
        'aria-orientation'?: "horizontal" | "vertical";
        'aria-owns'?: string;
        'aria-placeholder'?: string;
        'aria-posinset'?: number;
        'aria-pressed'?: boolean | "true" | "false" | "mixed";
        'aria-readonly'?: boolean | "true" | "false";
        'aria-relevant'?: "text" | "additions" | "additions text" | "all" | "removals";
        'aria-required'?: boolean | "true" | "false";
        'aria-roledescription'?: string;
        'aria-rowcount'?: number;
        'aria-rowindex'?: number;
        'aria-rowspan'?: number;
        'aria-selected'?: boolean | "true" | "false";
        'aria-setsize'?: number;
        'aria-sort'?: "none" | "ascending" | "descending" | "other";
        'aria-valuemax'?: number;
        'aria-valuemin'?: number;
        'aria-valuenow'?: number;
        'aria-valuetext'?: string;
        children?: React.ReactNode;
        dangerouslySetInnerHTML?: {
            __html: string;
        };
        onCopy?: (event: React.ClipboardEvent<HTMLInputElement>) => void;
        onCopyCapture?: (event: React.ClipboardEvent<HTMLInputElement>) => void;
        onCut?: (event: React.ClipboardEvent<HTMLInputElement>) => void;
        onCutCapture?: (event: React.ClipboardEvent<HTMLInputElement>) => void;
        onPaste?: (event: React.ClipboardEvent<HTMLInputElement>) => void;
        onPasteCapture?: (event: React.ClipboardEvent<HTMLInputElement>) => void;
        onCompositionEnd?: (event: React.CompositionEvent<HTMLInputElement>) => void;
        onCompositionEndCapture?: (event: React.CompositionEvent<HTMLInputElement>) => void;
        onCompositionStart?: (event: React.CompositionEvent<HTMLInputElement>) => void;
        onCompositionStartCapture?: (event: React.CompositionEvent<HTMLInputElement>) => void;
        onCompositionUpdate?: (event: React.CompositionEvent<HTMLInputElement>) => void;
        onCompositionUpdateCapture?: (event: React.CompositionEvent<HTMLInputElement>) => void;
        onFocus?: (event: React.FocusEvent<HTMLInputElement>) => void;
        onFocusCapture?: (event: React.FocusEvent<HTMLInputElement>) => void;
        onBlur?: (event: React.FocusEvent<HTMLInputElement>) => void;
        onBlurCapture?: (event: React.FocusEvent<HTMLInputElement>) => void;
        onChange?: (event: React.FormEvent<HTMLInputElement>) => void;
        onChangeCapture?: (event: React.FormEvent<HTMLInputElement>) => void;
        onBeforeInput?: (event: React.FormEvent<HTMLInputElement>) => void;
        onBeforeInputCapture?: (event: React.FormEvent<HTMLInputElement>) => void;
        onInput?: (event: React.FormEvent<HTMLInputElement>) => void;
        onInputCapture?: (event: React.FormEvent<HTMLInputElement>) => void;
        onReset?: (event: React.FormEvent<HTMLInputElement>) => void;
        onResetCapture?: (event: React.FormEvent<HTMLInputElement>) => void;
        onSubmit?: (event: React.FormEvent<HTMLInputElement>) => void;
        onSubmitCapture?: (event: React.FormEvent<HTMLInputElement>) => void;
        onInvalid?: (event: React.FormEvent<HTMLInputElement>) => void;
        onInvalidCapture?: (event: React.FormEvent<HTMLInputElement>) => void;
        onLoad?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onLoadCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onError?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onErrorCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onKeyDown?: (event: React.KeyboardEvent<HTMLInputElement>) => void;
        onKeyDownCapture?: (event: React.KeyboardEvent<HTMLInputElement>) => void;
        onKeyPress?: (event: React.KeyboardEvent<HTMLInputElement>) => void;
        onKeyPressCapture?: (event: React.KeyboardEvent<HTMLInputElement>) => void;
        onKeyUp?: (event: React.KeyboardEvent<HTMLInputElement>) => void;
        onKeyUpCapture?: (event: React.KeyboardEvent<HTMLInputElement>) => void;
        onAbort?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onAbortCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onCanPlay?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onCanPlayCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onCanPlayThrough?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onCanPlayThroughCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onDurationChange?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onDurationChangeCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onEmptied?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onEmptiedCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onEncrypted?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onEncryptedCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onEnded?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onEndedCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onLoadedData?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onLoadedDataCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onLoadedMetadata?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onLoadedMetadataCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onLoadStart?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onLoadStartCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onPause?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onPauseCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onPlay?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onPlayCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onPlaying?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onPlayingCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onProgress?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onProgressCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onRateChange?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onRateChangeCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onSeeked?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onSeekedCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onSeeking?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onSeekingCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onStalled?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onStalledCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onSuspend?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onSuspendCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onTimeUpdate?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onTimeUpdateCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onVolumeChange?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onVolumeChangeCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onWaiting?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onWaitingCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onAuxClick?: (event: React.MouseEvent<HTMLInputElement, MouseEvent>) => void;
        onAuxClickCapture?: (event: React.MouseEvent<HTMLInputElement, MouseEvent>) => void;
        onClickCapture?: (event: React.MouseEvent<HTMLInputElement, MouseEvent>) => void;
        onContextMenu?: (event: React.MouseEvent<HTMLInputElement, MouseEvent>) => void;
        onContextMenuCapture?: (event: React.MouseEvent<HTMLInputElement, MouseEvent>) => void;
        onDoubleClick?: (event: React.MouseEvent<HTMLInputElement, MouseEvent>) => void;
        onDoubleClickCapture?: (event: React.MouseEvent<HTMLInputElement, MouseEvent>) => void;
        onDrag?: (event: React.DragEvent<HTMLInputElement>) => void;
        onDragCapture?: (event: React.DragEvent<HTMLInputElement>) => void;
        onDragEnd?: (event: React.DragEvent<HTMLInputElement>) => void;
        onDragEndCapture?: (event: React.DragEvent<HTMLInputElement>) => void;
        onDragEnter?: (event: React.DragEvent<HTMLInputElement>) => void;
        onDragEnterCapture?: (event: React.DragEvent<HTMLInputElement>) => void;
        onDragExit?: (event: React.DragEvent<HTMLInputElement>) => void;
        onDragExitCapture?: (event: React.DragEvent<HTMLInputElement>) => void;
        onDragLeave?: (event: React.DragEvent<HTMLInputElement>) => void;
        onDragLeaveCapture?: (event: React.DragEvent<HTMLInputElement>) => void;
        onDragOver?: (event: React.DragEvent<HTMLInputElement>) => void;
        onDragOverCapture?: (event: React.DragEvent<HTMLInputElement>) => void;
        onDragStart?: (event: React.DragEvent<HTMLInputElement>) => void;
        onDragStartCapture?: (event: React.DragEvent<HTMLInputElement>) => void;
        onDrop?: (event: React.DragEvent<HTMLInputElement>) => void;
        onDropCapture?: (event: React.DragEvent<HTMLInputElement>) => void;
        onMouseDown?: (event: React.MouseEvent<HTMLInputElement, MouseEvent>) => void;
        onMouseDownCapture?: (event: React.MouseEvent<HTMLInputElement, MouseEvent>) => void;
        onMouseEnter?: (event: React.MouseEvent<HTMLInputElement, MouseEvent>) => void;
        onMouseLeave?: (event: React.MouseEvent<HTMLInputElement, MouseEvent>) => void;
        onMouseMove?: (event: React.MouseEvent<HTMLInputElement, MouseEvent>) => void;
        onMouseMoveCapture?: (event: React.MouseEvent<HTMLInputElement, MouseEvent>) => void;
        onMouseOut?: (event: React.MouseEvent<HTMLInputElement, MouseEvent>) => void;
        onMouseOutCapture?: (event: React.MouseEvent<HTMLInputElement, MouseEvent>) => void;
        onMouseOver?: (event: React.MouseEvent<HTMLInputElement, MouseEvent>) => void;
        onMouseOverCapture?: (event: React.MouseEvent<HTMLInputElement, MouseEvent>) => void;
        onMouseUp?: (event: React.MouseEvent<HTMLInputElement, MouseEvent>) => void;
        onMouseUpCapture?: (event: React.MouseEvent<HTMLInputElement, MouseEvent>) => void;
        onSelect?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onSelectCapture?: (event: React.SyntheticEvent<HTMLInputElement, Event>) => void;
        onTouchCancel?: (event: React.TouchEvent<HTMLInputElement>) => void;
        onTouchCancelCapture?: (event: React.TouchEvent<HTMLInputElement>) => void;
        onTouchEnd?: (event: React.TouchEvent<HTMLInputElement>) => void;
        onTouchEndCapture?: (event: React.TouchEvent<HTMLInputElement>) => void;
        onTouchMove?: (event: React.TouchEvent<HTMLInputElement>) => void;
        onTouchMoveCapture?: (event: React.TouchEvent<HTMLInputElement>) => void;
        onTouchStart?: (event: React.TouchEvent<HTMLInputElement>) => void;
        onTouchStartCapture?: (event: React.TouchEvent<HTMLInputElement>) => void;
        onPointerDown?: (event: React.PointerEvent<HTMLInputElement>) => void;
        onPointerDownCapture?: (event: React.PointerEvent<HTMLInputElement>) => void;
        onPointerMove?: (event: React.PointerEvent<HTMLInputElement>) => void;
        onPointerMoveCapture?: (event: React.PointerEvent<HTMLInputElement>) => void;
        onPointerUp?: (event: React.PointerEvent<HTMLInputElement>) => void;
        onPointerUpCapture?: (event: React.PointerEvent<HTMLInputElement>) => void;
        onPointerCancel?: (event: React.PointerEvent<HTMLInputElement>) => void;
        onPointerCancelCapture?: (event: React.PointerEvent<HTMLInputElement>) => void;
        onPointerEnter?: (event: React.PointerEvent<HTMLInputElement>) => void;
        onPointerEnterCapture?: (event: React.PointerEvent<HTMLInputElement>) => void;
        onPointerLeave?: (event: React.PointerEvent<HTMLInputElement>) => void;
        onPointerLeaveCapture?: (event: React.PointerEvent<HTMLInputElement>) => void;
        onPointerOver?: (event: React.PointerEvent<HTMLInputElement>) => void;
        onPointerOverCapture?: (event: React.PointerEvent<HTMLInputElement>) => void;
        onPointerOut?: (event: React.PointerEvent<HTMLInputElement>) => void;
        onPointerOutCapture?: (event: React.PointerEvent<HTMLInputElement>) => void;
        onGotPointerCapture?: (event: React.PointerEvent<HTMLInputElement>) => void;
        onGotPointerCaptureCapture?: (event: React.PointerEvent<HTMLInputElement>) => void;
        onLostPointerCapture?: (event: React.PointerEvent<HTMLInputElement>) => void;
        onLostPointerCaptureCapture?: (event: React.PointerEvent<HTMLInputElement>) => void;
        onScroll?: (event: React.UIEvent<HTMLInputElement>) => void;
        onScrollCapture?: (event: React.UIEvent<HTMLInputElement>) => void;
        onWheel?: (event: React.WheelEvent<HTMLInputElement>) => void;
        onWheelCapture?: (event: React.WheelEvent<HTMLInputElement>) => void;
        onAnimationStart?: (event: React.AnimationEvent<HTMLInputElement>) => void;
        onAnimationStartCapture?: (event: React.AnimationEvent<HTMLInputElement>) => void;
        onAnimationEnd?: (event: React.AnimationEvent<HTMLInputElement>) => void;
        onAnimationEndCapture?: (event: React.AnimationEvent<HTMLInputElement>) => void;
        onAnimationIteration?: (event: React.AnimationEvent<HTMLInputElement>) => void;
        onAnimationIterationCapture?: (event: React.AnimationEvent<HTMLInputElement>) => void;
        onTransitionEnd?: (event: React.TransitionEvent<HTMLInputElement>) => void;
        onTransitionEndCapture?: (event: React.TransitionEvent<HTMLInputElement>) => void;
        key?: string | number;
    };
    render(): JSX.Element;
}
export {};
